// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebbctvzcnrteuufarlfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYmN0dnpjbnJ0ZXV1ZmFybGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTA4OTMsImV4cCI6MjA1NzkyNjg5M30.sfzLQDdIyKfMnb1mu25YH_zazejOOiGk6VBvBBqG6Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);